project:
  type: website
  output-dir: docs

website:
  title: "Creating a website using Quarto For Lab 2 Question 4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



